site_name: TheMoeWay - Tiếng Việt
site_description: Moe Moe Moe Moe Moe Moe Moe (Nhưng là bản dịch Tiếng Việt)
site_author: shoui  

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn':
    - 'Hướng dẫn chính': 'guide.md'
    - '30 ngày Tiếng Nhật': 'routine.md'
    - 'speaking.md'
    - 'animejp.md'
    - 'kanji.md'
    - 'readingtips.md'
    - 'monolingual.md'
    - 'faq.md'
    - 'Sửa phông chữ': 'font.md'
  - 'Visual Novel':
    - 'Học Tiếng Nhật bằng VN': 'vn.md'
    - 'Cài đặt Visual Novel': 'vn-setup.md'
  - 'Yomitan':
    - 'Hướng dẫn cài đặt Yomitan': 'yomichan.md'      
  - 'Tài nguyên':
    - 'Tài nguyên': 'resources.md' 
    - 'Tham gia cộng đồng': 'join.md'
  - 'Khác':
    - 'Donate': 'donate.md'
theme:
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: cyan 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material
  favicon: img/favicon.png
  logo: img/moe.svg
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - en
        - vi
        - ja
  - open-in-new-tab

extra:
  generator: false
  alternate:
    - name: English
      link: https://learnjapanese.moe/
      lang: en
    - name: Tiếng Việt
      link: /
      lang: vi
